api: false
custom_fewshots_template: null
custom_prompt_template: null
dataset_artifact: wandb-japan/llm-leaderboard/jaster:v3
dataset_dir: /jaster/1.1.0/evaluation/test
generator:
  repetition_penalty: 1.0
  temperature: 0.1
  top_k: 0
  top_p: 1.0
github_version: v2.0.0
log_dir: ./logs
max_seq_length: 1024
metainfo:
  basemodel_name: test
  instruction_tuning_data:
  - None
  instruction_tuning_method: None
  llm-jp-eval-version: 1.1.0
  model_type: open llm
  num_few_shots: 0
model:
  artifacts_path: ''
  device_map: auto
  load_in_4bit: false
  load_in_8bit: false
  pretrained_model_name_or_path: ../../data/model/test
  trust_remote_code: true
  use_wandb_artifacts: false
mtbench:
  baseline_model: null
  bench_name: japanese_mt_bench
  conv_name: custom
  conv_role_message_separator: ": \n"
  conv_role_only_separator: ": \n"
  conv_roles: "('\u6307\u793A', '\u5FDC\u7B54')"
  conv_sep: '


    ### '
  conv_stop_str: '###'
  conv_stop_token_ids: '[2]'
  conv_system_message: "\u4EE5\u4E0B\u306F\u3001\u30BF\u30B9\u30AF\u3092\u8AAC\u660E\
    \u3059\u308B\u6307\u793A\u3068\u3001\u6587\u8108\u306E\u3042\u308B\u5165\u529B\
    \u306E\u7D44\u307F\u5408\u308F\u305B\u3067\u3059\u3002\u8981\u6C42\u3092\u9069\
    \u5207\u306B\u6E80\u305F\u3059\u5FDC\u7B54\u3092\u66F8\u304D\u306A\u3055\u3044\
    \u3002"
  custom_conv_template: false
  dtype: bfloat16
  first_n: null
  judge_model: gpt-4
  judge_prompt_artifacts_path: wandb-japan/llm-leaderboard/mtbench_ja_prompt:v1
  max_gpu_memory: null
  max_new_token: 256
  mode: single
  model_id: null
  num_choices: 1
  num_gpus_per_model: 1
  num_gpus_total: 1
  parallel: 1
  question_artifacts_path: wandb-japan/llm-leaderboard/mtbench_ja_question:v0
  question_begin: null
  question_end: null
  referenceanswer_artifacts_path: wandb-japan/llm-leaderboard/mtbench_ja_referenceanswer:v0
target_dataset: all
testmode: false
tokenizer:
  artifacts_path: ''
  pretrained_model_name_or_path: ../../data/model/test
  use_fast: true
  use_wandb_artifacts: false
torch_dtype: bf16
wandb:
  entity: kanhatakeyamas
  log: true
  project: llmeval
  run_name: 20240323_005501test
