api: false
custom_fewshots_template: null
custom_prompt_template: null
dataset_artifact: wandb-japan/llm-leaderboard/jaster:v3
dataset_dir: /jaster/1.1.0/evaluation/test
generator:
  repetition_penalty: 1.0
  temperature: 0.1
  top_k: 0
  top_p: 1.0
github_version: v2.0.0
log_dir: ./logs
max_seq_length: 1024
metainfo:
  basemodel_name: llm-jp-llm-jp-13b-v1-0_inst_dolly14000_lr_5e-6
  instruction_tuning_data:
  - None
  instruction_tuning_method: None
  llm-jp-eval-version: 1.1.0
  model_type: open llm
  num_few_shots: 0
model:
  artifacts_path: ''
  device_map: auto
  load_in_4bit: false
  load_in_8bit: false
  pretrained_model_name_or_path: ../../model/llm-jp-llm-jp-13b-v1-0_inst_dolly14000_lr_5e-6
  trust_remote_code: true
  use_wandb_artifacts: false
mtbench:
  baseline_model: null
  bench_name: japanese_mt_bench
  conv_name: custom
  conv_role_message_separator: ": \n"
  conv_role_only_separator: ": \n"
  conv_roles: ('指示', '応答')
  conv_sep: '


    ### '
  conv_stop_str: '###'
  conv_stop_token_ids: '[2]'
  conv_system_message: 以下は、タスクを説明する指示と、文脈のある入力の組み合わせです。要求を適切に満たす応答を書きなさい。
  custom_conv_template: false
  dtype: bfloat16
  first_n: null
  judge_model: gpt-4
  judge_prompt_artifacts_path: wandb-japan/llm-leaderboard/mtbench_ja_prompt:v1
  max_gpu_memory: null
  max_new_token: 256
  mode: single
  model_id: null
  num_choices: 1
  num_gpus_per_model: 1
  num_gpus_total: 1
  parallel: 1
  question_artifacts_path: wandb-japan/llm-leaderboard/mtbench_ja_question:v0
  question_begin: null
  question_end: null
  referenceanswer_artifacts_path: wandb-japan/llm-leaderboard/mtbench_ja_referenceanswer:v0
target_dataset: all
testmode: false
tokenizer:
  artifacts_path: ''
  pretrained_model_name_or_path: ../../model/llm-jp-llm-jp-13b-v1-0_inst_dolly14000_lr_5e-6
  use_fast: true
  use_wandb_artifacts: false
torch_dtype: bf16
wandb:
  entity: kanhatakeyamas
  log: true
  project: llmeval
  run_name: 20240327_162844llm-jp-llm-jp-13b-v1-0_inst_dolly14000_lr_5e-6
