base_model: hatakeyama-llm-team/Tanuki_pretrained_stage6_step62160
#gate_mode: cheap_embed
gate_mode: hidden 
dtype: bfloat16 
experts:
  - source_model: hatakeyama-llm-team/Tanuki_pretrained_stage6_step62160
    positive_prompts:
      - 日本語
      - 評価
      - 作成
      - 情報
  - source_model: ../model/0516code_hatakeyama-llm-team-Tanuki_pretrained_stage6_step62160_inst_0516code-0code_10000000000-parquet_lr_5e-5
    positive_prompts:
      - Python
      - python
      - code
      - コード
      - JSON
      - Java
      - XML
      - csv
      - CSV
      - def
      - class
      - YAML
      - yaml
      - 関数
      - クラス
      - list
      - html
      - HTML
      - プログラム
      - スクリプト
      - script
      - Script
      - 計算
      - 数
      - いくつ
      - C
      - C++
      - C#
      - JavaScript
      - TypeScript
      - SQL
      - R
      - Ruby
      - Perl

