base_model: hatakeyama-llm-team/with_halcination_epoch4_ck10400
#gate_mode: cheap_embed
#gate_mode: hidden 
gate_mode: random
dtype: bfloat16 
experts:
 # - source_model: hatakeyama-llm-team/Tanuki-Soup-Test-v2
 #   positive_prompts:
 #     - 指示
  - source_model: hatakeyama-llm-team/with_halcination_epoch4_ck10400
    positive_prompts:
      - 指示
  - source_model: /home/hatakeyama/python/EvalPractice/X_merge/merged_models/hayashi_0529tk-dpo-test-lr5e-6-beta0.01
    positive_prompts:
      - 指示




