base_model: hatakeyama-llm-team/Tanuki_pretrained_stage6_step62160
#gate_mode: cheap_embed
gate_mode: hidden 
dtype: bfloat16 
experts:
  - source_model: hatakeyama-llm-team/Tanuki_pretrained_stage6_step62160
    positive_prompts:
      - 指示
  - source_model: ../../llm/models/hf/3_step43400
    positive_prompts:
      - 指示
  - source_model: ../../llm/models/hf/1_step30800
    positive_prompts:
      - Python
      - コード